import '@alice/client/assets/styles/index.scss'
import React from 'react'
import { Inter } from 'next/font/google'
import { AntdRegistry } from '@ant-design/nextjs-registry'
import { getServerSession } from 'next-auth/next'
import { authOptions } from '../auth/auth.config'
import Provider from '../auth/SessionProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions)
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdRegistry>
          <Provider session={session}>{children}</Provider>
        </AntdRegistry>
      </body>
    </html>
  )
}
