name: Deploy to CentOS Server

on:
  push:
    branches:
      - develop

jobs:
  deploy:
     runs-on: CentOS-7

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          mkdir -p packages/server
          echo "MYSQL_DB_HOST=${{ secrets.SERVER_HOST }}" >> packages/server/.env
          echo "MYSQL_DB_PORT=my_username" >> packages/server/.env
          echo "MYSQL_DB_USER=my_password" >> packages/server/.env
          echo "MYSQL_DB_PASSWD=my_password" >> packages/server/.env
          echo "MYSQL_DB_DATABASE=my_password" >> packages/server/.env
          echo "NODE_ENV=my_password" >> packages/server/.env
          echo "JWTSECRET=my_password" >> packages/server/.env
          echo "REDIS_HOST=my_password" >> packages/server/.env
          echo "REDIS_PORT=my_password" >> packages/server/.env
          echo "REDIS_PASSWD=my_password" >> packages/server/.env

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: './'
          target: /home/Alice
          
        - name: SSH to server and restart application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /home/Alice
            pnpm install
            npm run build
            pm2 start ./packages/server/dist/main.js --name alice-serve -i max
